In [1]:
import pandas as pd
import numpy as np

## Q1:  What version of Numpy you installed

In [2]:
np.__version__

'1.20.3'

In [3]:
df =pd.read_csv('ml.csv')

## Q2: How many records are in the dataset?

In [4]:
len(df)

11914

## Q3: Who are the most frequent car manufacturers (top-3) according to the dataset?

In [5]:
df['Make'].value_counts()

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker    

#### chevrolet, Ford and voltswagen

## Q4: What's the number of unique Audi car models in the dataset?

In [6]:
df[df['Make'] == 'Audi'].nunique()

Make                   1
Model                 34
Year                  20
Engine Fuel Type       5
Engine HP             40
Engine Cylinders       6
Transmission Type      3
Driven_Wheels          2
Number of Doors        2
Market Category       15
Vehicle Size           3
Vehicle Style          6
highway MPG           23
city mpg              18
Popularity             1
MSRP                 234
dtype: int64

### 34

## Q5:How many columns in the dataset have missing values?

In [7]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

### 5

## Q6:Find the median value of "Engine Cylinders" column in the dataset.
 ### Next, calculate the most frequent value of the same "Engine Cylinders".
 ### Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
 ### Now, calculate the median value of "Engine Cylinders" once again

In [8]:
df["Engine Cylinders"].median()

6.0

In [9]:
df["Engine Cylinders"].value_counts()

4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

In [10]:
df["Engine Cylinders"]=df["Engine Cylinders"].fillna(4)

In [11]:
df["Engine Cylinders"].median()

6.0

#### no changes in the values of median before and after the missing values has filled up

## Q 7: Select all the "Lotus" cars from the dataset.
   ### Select only columns "Engine HP", "Engine Cylinders".
  ### Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
 ### Get the underlying NumPy array. Let's call it X.
### Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
### Invert XTX.
### Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
### Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
 ## What's the value of the first element of w?


In [12]:
df_new = df[df.Make== 'Lotus'][["Engine Cylinders","Engine HP"]].drop_duplicates()

In [13]:
df_new

Engine Cylinders  Engine HP
3912               4.0      189.0
3913               4.0      218.0
3918               4.0      217.0
4216               8.0      350.0
4257               6.0      400.0
4259               6.0      276.0
4262               6.0      345.0
4292               4.0      257.0
4293               4.0      240.0

In [14]:
X =df_new.values

In [15]:
X

array([[  4., 189.],
       [  4., 218.],
       [  4., 217.],
       [  8., 350.],
       [  6., 400.],
       [  6., 276.],
       [  6., 345.],
       [  4., 257.],
       [  4., 240.]])

In [16]:
XTX = X.T.dot(X)

In [17]:
XTX

array([[2.52000e+02, 1.34100e+04],
       [1.34100e+04, 7.31684e+05]])

In [18]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 1.60588447e-01, -2.94319825e-03],
       [-2.94319825e-03,  5.53084235e-05]])

In [19]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

In [20]:
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [21]:
w = XTX_inv.dot(X.T).dot(y)

In [22]:
w

array([-63.56432501,   4.59494481])